### ISSUE TITLE
Remote processes need to be considered in the OpenAPI spec

### ISSUE THREAD

**Issue by francbartoli** [opengeospatial/wps-rest-binding#35]
I'd like to declare a process as executed remotely, something like:

```yaml
process:
    allOf:
       - $ref: 'processSummary.yaml'
       - type: object
         required:
           - id
         properties:
            provider:
              type: string
            inputs:
              type: array
              items: 
                 $ref: 'inputDescription.yaml'
            outputs:
              type: array
              items: 
                 $ref: 'outputDescription.yaml'
            links:
              type: array
              items:
                 $ref: 'link.yaml'
```

`provider` might be simply `local` or remote with the name (for instance `Google Earth Engine` or `GeoScope`) of the cloud infrastructure
