### ISSUE TITLE
Added missing attribute for referenceValue

### ISSUE THREAD

**Issue by spacebel** [opengeospatial/wps-rest-binding#43]
Added mime type, schema and encoding attribute in referenceValue.
This is highly needed for providing input in a specific format or returning output in a specific format.
https://github.com/opengeospatial/wps-rest-binding/commit/5076baaf581e650f12ad2bd2b9f17adb8f157a8e

**Comment by bpross-52n** [comment]
The complexData element has a dataType element, which specifies the format

````
complexData:
    allOf:
       - $ref: 'dataType.yaml'
       - type: object
         required:
            - value
         properties:
            value:
               $ref: 'valueType.yaml'
````

Source: https://github.com/opengeospatial/wps-rest-binding/blob/master/core/openapi/schemas/complexData.yaml

Example:

````
{
    "inputs": [
        {
            "id": "data",
            "input": {
                "format": {
                    "mimeType": "text/xml",
                    "schema": "http://schemas.opengis.net/gml/3.1.1/base/feature.xsd"
                },
                "value": {
                    "href": "http://geoprocessing.demo.52north.org:8080/geoserver/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=topp:tasmania_roads&SRS=EPSG:4326&OUTPUTFORMAT=GML3"
                }
            }
        },
        {
            "id": "width",
            "input": {
                "format": {
                    "mimeType": "text/plain"
                },
                "value": {
                    "inlineValue": "0.05"
                }
            }
        }
    ],
    "outputs": [
        {
            "id": "result",
            "format": {
                "mimeType": "text/xml",
                "schema": "http://schemas.opengis.net/gml/3.1.1/base/feature.xsd"
            },
            "transmissionMode": "reference"
        }
    ]
}
````
